import Link from "next/link";
import {
  ArrowRight,
  Bot,
  Check,
  Code2,
  CreditCard,
  FileCheck2,
  Globe2,
  LockKeyhole,
  Network,
  Package,
  ReceiptText,
  ShieldCheck,
  ShoppingBag,
  Store,
  WalletCards,
} from "lucide-react";
import { MotionReveal } from "@/components/motion-reveal";
import { CaravelMark } from "@/components/caravel-mark";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import motion from "@/components/landing-motion.module.css";

const sources = [
  [Code2, "OpenAPI", "18 operations"],
  [Store, "Commerce", "Products and variants"],
  [CreditCard, "Billing", "Plans and prices"],
  [Globe2, "Custom API", "Internal catalog"],
] as const;

function HeroWorkspacePreview() {
  return <div className={`mx-auto mt-16 max-w-[78rem] overflow-hidden rounded-2xl border border-white/10 bg-[#090d0d] text-left shadow-[0_36px_120px_rgba(0,0,0,0.48)] ${motion.heroVisual}`}>
    <div className="flex h-12 items-center justify-between border-b border-white/10 px-4 sm:px-5"><div className="flex items-center gap-2"><CaravelMark className="size-7" /><span className="text-sm font-medium">Commerce workspace</span></div><div className="flex items-center gap-2"><Badge variant="outline">Buying</Badge><Badge variant="outline">Selling</Badge></div></div>
    <div className="grid min-h-[29rem] lg:grid-cols-[13rem_1fr_18rem]">
      <div className="hidden border-r border-white/10 p-4 lg:block"><p className="px-2 text-sm text-muted-foreground">Workspace</p><div className="mt-3 space-y-1">{([[Package,"Products"],[ShoppingBag,"Purchases"],[ReceiptText,"Approvals"],[WalletCards,"Payments"]] as const).map(([Glyph,label],index) => { const Icon = Glyph as typeof Package; return <div key={String(label)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${index === 0 ? "bg-white/[0.07] text-foreground" : "text-muted-foreground"}`}><Icon className="size-4" />{label}</div>; })}</div><div className="mt-8 border-t border-white/10 pt-5"><p className="px-2 text-sm text-muted-foreground">Connections</p><div className="mt-3 space-y-3 px-2">{["Rain","Monad","OpenAI"].map(name => <div key={name} className="flex items-center justify-between text-sm"><span>{name}</span><span className="text-primary">Connected</span></div>)}</div></div></div>
      <div className="p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-sm text-muted-foreground">Product catalog</p><h3 className="mt-1 text-xl font-semibold">Everything your business sells</h3></div><Button size="sm">Add source</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["24","Products"],["4","Connected sources"],["18","Published to agents"]].map(([value,label]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>)}</div><div className="mt-5 overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/10 bg-white/[0.025] px-4 py-3 text-sm text-muted-foreground"><span>Product</span><span>Payment</span><span>Status</span></div>{[["Risk assessment API","Monad x402"],["Team software","Subscription"],["Equipment package","Rain or escrow"],["Compliance service","Rain or invoice"]].map(([product,payment],index) => <div key={product} style={{ animationDelay: `${.7 + index * .12}s` }} className={`grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-white/10 px-4 py-4 text-sm last:border-0 ${motion.statusStep}`}><div><p className="font-medium">{product}</p><p className="mt-1 text-muted-foreground">Policy enforced</p></div><span className="hidden text-muted-foreground sm:block">{payment}</span><Badge variant="secondary">Live</Badge></div>)}</div></div>
      <div className="border-t border-white/10 bg-white/[0.018] p-5 lg:border-l lg:border-t-0"><div className="flex items-start gap-3"><Bot className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-sm font-medium">Buying agent</p><p className="text-sm text-muted-foreground">Waiting for instructions</p></div></div><div className="mt-5 border-l border-white/15 pl-4 text-sm leading-6 text-foreground/90">Find a compliant data provider for 10,000 requests. Keep spend below $300 and ask before using a new vendor.</div><div className="mt-5 space-y-3.5">{([[Check,"Mandate prepared"],[Network,"3 sellers compared"],[ShieldCheck,"Company policy passed"],[FileCheck2,"Waiting for approval"]] as const).map(([Glyph,label],index) => { const Icon = Glyph as typeof Check; return <div key={label} style={{ animationDelay: `${1.4 + index * .22}s` }} className={`flex items-center gap-3 text-sm ${motion.statusStep}`}><Icon className={`size-4 ${index < 3 ? "text-primary" : "text-muted-foreground"}`} />{label}</div>; })}</div><Button className="mt-7 w-full">Review purchase</Button></div>
    </div>
  </div>;
}

function BuyingIllustration() {
  return <div className="mt-7 overflow-hidden rounded-xl border border-white/10 bg-black/20">
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-sm"><span className="text-muted-foreground">Procurement request</span><span className="text-primary">Approval required</span></div>
    <div className="p-4"><div className="border-l border-white/20 pl-4 text-sm leading-6">Buy compliance and weather coverage for 10,000 API calls. Keep total spend below $300.</div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_2rem_1fr_2rem_1fr] sm:items-stretch"><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">MANDATE</p><p className="mt-3 text-sm font-medium">Budget and requirements extracted</p><p className="mt-2 text-sm text-muted-foreground">$300 maximum · approved data only</p></div><div data-motion-line className={`hidden items-center sm:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">MARKET</p><p className="mt-3 text-sm font-medium">3 qualified sellers</p><div className="mt-3 flex items-center justify-between gap-3 text-sm text-primary"><span>Best offer</span><span className="shrink-0">$284</span></div><div className="mt-2 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>Next best</span><span className="shrink-0">$296</span></div></div><div data-motion-line className={`hidden items-center sm:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">DECISION</p><p className="mt-3 text-sm font-medium">MissionClear selected</p><p className="mt-2 text-sm text-muted-foreground">Rules passed · payment paused</p></div></div></div>
    <div className="flex items-center justify-between border-t border-white/10 bg-white/[0.018] px-4 py-3 text-sm"><span className="flex items-center gap-2"><FileCheck2 className="size-4 text-muted-foreground" />Human review</span><span className="font-medium">Approve $284</span></div>
  </div>;
}

function SellingIllustration() {
  return <div className="mt-7 overflow-hidden rounded-xl border border-white/10 bg-black/20">
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-sm"><span className="text-muted-foreground">PreFlight OpenAPI imported</span><span>18 operations</span></div>
    <div className="p-4"><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">IMPORTED CATALOG</p><div className="mt-3 grid gap-2 font-mono text-xs sm:grid-cols-3"><p>GET /weather/metars</p><p>GET /airspace/notams</p><p>POST /mission/readiness</p></div></div><div className="relative mt-3 h-7 border-l border-white/15 sm:ml-8"><span className={`${motion.verticalTrace} absolute inset-y-0 left-[-1px] w-px`} /></div><div className="grid gap-4 sm:grid-cols-[1fr_2rem_1fr] sm:items-stretch"><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">COMMERCIAL RULES</p><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-3"><span>Weather</span><span>$0.01</span></div><div className="flex justify-between gap-3"><span>Airspace</span><span>$0.03</span></div><div className="flex justify-between gap-3"><span>Assessment</span><span>$0.25</span></div></div></div><div data-motion-line className={`hidden items-center sm:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div><div data-motion-stage className={`${motion.businessStage} border-y border-white/10 py-4`}><p className="font-mono text-xs text-muted-foreground">AGENT CHANNEL</p><p className="mt-3 text-sm font-medium">Published for discovery</p><p className="mt-2 text-sm text-muted-foreground">Price floor and payment method travel with every operation.</p></div></div></div>
    <div className="flex items-center justify-between border-t border-white/10 bg-white/[0.018] px-4 py-3 text-sm"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-muted-foreground" />Pricing policy enforced</span><span className="text-primary">Available to buyers</span></div>
  </div>;
}

function ConnectionIllustration() {
  return <div className="mt-14 overflow-hidden rounded-2xl border border-white/10 bg-[#090e0e] shadow-[0_24px_80px_rgba(0,0,0,0.28)]">
    <div className="border-b border-white/10 px-6 py-4 md:px-8"><p className="text-sm font-medium">One company configuration becomes agent-ready commerce</p></div>
    <div className="grid gap-5 p-6 md:p-8 lg:grid-cols-[1fr_4rem_1.15fr_4rem_1fr] lg:items-center">
      <div><p className="mb-4 font-mono text-xs text-muted-foreground">EXISTING BUSINESS SYSTEMS</p><div className="space-y-2">{sources.map(([Glyph,title,detail]) => { const Icon = Glyph; return <div data-motion-stage key={title} className={`${motion.businessStage} flex items-center justify-between border-b border-white/10 py-3`}><div className="flex items-center gap-3"><Icon className="size-4 text-muted-foreground" /><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></div><Check className="size-4 text-primary" /></div>; })}</div></div>

      <div data-motion-line className={`hidden items-center lg:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div>

      <div data-motion-control className={`${motion.controlStage} border border-white/15 bg-white/[0.025] p-5`}><div className="flex items-center gap-3"><CaravelMark className="size-8" /><div><p className="text-sm font-medium">Unified commerce configuration</p><p className="text-xs text-muted-foreground">Generated from your connected systems</p></div></div><div className="mt-5 border-y border-white/10 font-mono text-xs leading-7 text-muted-foreground"><p><span className="text-foreground">product</span> API and physical goods</p><p><span className="text-foreground">price</span> per call, plan, or order</p><p><span className="text-foreground">negotiate</span> within approved boundaries</p><p><span className="text-foreground">payment</span> x402, Rain, or checkout</p><p><span className="text-foreground">approval</span> required above company limit</p></div><div className="mt-5 flex items-center justify-between text-xs"><span className="text-muted-foreground">Policy validation</span><span className="text-primary">Passed</span></div></div>

      <div data-motion-line className={`hidden items-center lg:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div>

      <div><p className="mb-4 font-mono text-xs text-muted-foreground">PUBLISHED OUTPUT</p><div className="space-y-2">{([[Package,"Agent catalog","Products and API operations"],[Bot,"Buying and selling skills","Natural-language workflows"],[ShieldCheck,"Commerce policy","Budgets, prices, and approvals"],[CreditCard,"Payment routes","Monad, Rain, and checkout"]] as const).map(([Glyph,title,detail]) => { const Icon = Glyph as typeof Package; return <div data-motion-stage key={String(title)} className={`${motion.businessStage} flex gap-3 border-b border-white/10 py-3`}><Icon className="mt-0.5 size-4 shrink-0 text-muted-foreground" /><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></div>; })}</div></div>
    </div>
    <div className="grid grid-cols-2 border-t border-white/10 text-xs text-muted-foreground sm:grid-cols-4"><span className="border-r border-white/10 px-6 py-3">4 sources connected</span><span className="border-r border-white/10 px-6 py-3">24 products normalized</span><span className="border-r border-white/10 px-6 py-3">18 API operations</span><span className="px-6 py-3 text-primary">Ready for agents</span></div>
  </div>;
}

function RailIllustration() {
  const routes = [
    [Code2,"GET /weather/metars","Machine purchase","$0.01",WalletCards,"Monad x402","Settled on testnet"],
    [ReceiptText,"Vendor data package","Controlled procurement","$284",CreditCard,"Rain scoped card","Approved merchant only"],
    [Package,"XAG P100 Pro bundle","High-value equipment","$28,900",LockKeyhole,"Escrow or checkout","Funds released on delivery"],
  ] as const;
  return <div className="mt-12 overflow-hidden rounded-2xl border border-white/10 bg-[#090e0e]">
    <div className="grid border-b border-white/10 px-5 py-4 text-xs text-muted-foreground sm:grid-cols-[1.25fr_7rem_1fr] md:px-7"><span>Approved purchase</span><span className="hidden text-center sm:block">Route</span><span className="hidden sm:block">Payment method</span></div>
    <div>{routes.map(([SourceIcon,item,kind,amount,RailIcon,rail,result]) => <div data-motion-route key={item} className={`${motion.routeRow} grid gap-4 border-b border-white/10 px-5 py-5 last:border-0 sm:grid-cols-[1.25fr_7rem_1fr] sm:items-center md:px-7`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><SourceIcon className="mt-0.5 size-4 shrink-0 text-muted-foreground" /><div><p className="text-sm font-medium">{item}</p><p className="mt-1 text-xs text-muted-foreground">{kind}</p></div></div><span className="font-mono text-xs text-muted-foreground">{amount}</span></div><div data-motion-line className={`hidden items-center sm:flex ${motion.flowLine}`}><ArrowRight className="ml-auto size-4 text-muted-foreground" /></div><div className="flex gap-3"><RailIcon className="mt-0.5 size-4 shrink-0 text-muted-foreground" /><div><p className="text-sm font-medium">{rail}</p><p className="mt-1 text-xs text-muted-foreground">{result}</p></div></div></div>)}</div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 bg-white/[0.018] px-5 py-4 text-xs md:px-7"><span className="text-muted-foreground">The company policy selects the rail before authorization.</span><span className="text-primary">Every route remains auditable</span></div>
  </div>;
}

export function LandingPage() {
  const headline = [["Connect","your","business."],["Let","agents","transact."]];
  let wordIndex = 0;

  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-border bg-background/88 backdrop-blur-2xl"><div className="mx-auto flex h-[4.5rem] max-w-[90rem] items-center justify-between px-5 md:px-8"><Link href="/" className="flex items-center gap-3"><CaravelMark className="size-9" /><div><p className="text-base font-semibold tracking-tight">Caravel</p><p className="text-sm text-muted-foreground">API product infrastructure</p></div></Link><nav className="hidden items-center gap-7 text-sm text-muted-foreground lg:flex"><a href="#platform" className="hover:text-foreground">Platform</a><a href="#connect" className="hover:text-foreground">Connect anything</a><a href="#rails" className="hover:text-foreground">Payment rails</a></nav><div className="flex items-center gap-2"><Button asChild size="sm" variant="ghost" className="hidden sm:inline-flex"><Link href="/api/openapi">API</Link></Button><Button asChild size="sm"><Link href="/dashboard">Open dashboard<ArrowRight /></Link></Button></div></div></header>

    <main>
      <section className="relative px-5 pb-20 pt-36 md:px-8 md:pb-28 md:pt-44"><div aria-hidden="true" className="absolute left-1/2 top-0 h-[34rem] w-[70rem] max-w-full -translate-x-1/2 bg-[radial-gradient(ellipse,hsl(58_100%_65%/0.1),hsl(185_80%_55%/0.035)_45%,transparent_72%)] blur-3xl" /><div className="relative mx-auto max-w-6xl text-center"><Badge variant="outline">Turn an API into an agent-ready product</Badge><h1 className="mx-auto mt-7 max-w-5xl text-5xl font-semibold tracking-[-0.055em] sm:text-6xl md:text-[5.4rem] md:leading-[.96]">{headline.map((line,lineIndex) => <span key={lineIndex} className="block overflow-hidden">{line.map(word => { const delay = .08 + wordIndex++ * .09; return <span key={word} style={{ animationDelay: `${delay}s` }} className={`${motion.heroWord} mr-[.2em]`}>{word}</span>; })}</span>)}</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-muted-foreground md:text-xl">Connect the APIs, products, payment providers, and policies your company already uses. Caravel turns API operations into products that agents can discover, pay for, and use.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/dashboard">Explore the platform<ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/dashboard?demo=workspace">Run the working demo</Link></Button></div><div className="mt-9 flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm text-muted-foreground"><span><strong className="text-foreground">18</strong> callable API products</span><span><strong className="text-foreground">2</strong> commerce directions</span><span><strong className="text-foreground">1</strong> policy layer</span></div><HeroWorkspacePreview /></div></section>

      <section id="platform" className="border-y border-border bg-black/10 px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><MotionReveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold text-primary">One platform, both sides of commerce</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] md:text-5xl">Your company can buy and sell through agents.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Every agent operates inside the same budgets, pricing floors, approvals, payment choices, and audit trail.</p></MotionReveal><div className="mt-14 grid gap-5 lg:grid-cols-2"><MotionReveal><div className={`h-full rounded-2xl border border-border bg-card p-7 md:p-8 ${motion.flowCard}`}><div className="flex items-center gap-3"><ShoppingBag className="size-5 text-muted-foreground" /><h3 className="text-2xl font-semibold">Buying</h3></div><p className="mt-4 leading-7 text-muted-foreground">Describe the outcome. The agent prepares a mandate, compares sellers, enforces company rules, and stops for approval.</p><BuyingIllustration /></div></MotionReveal><MotionReveal delay={160}><div className={`h-full rounded-2xl border border-border bg-card p-7 md:p-8 ${motion.flowCard}`}><div className="flex items-center gap-3"><Store className="size-5 text-muted-foreground" /><h3 className="text-2xl font-semibold">Selling</h3></div><p className="mt-4 leading-7 text-muted-foreground">Import what you already sell, price every product or operation, compile negotiation rules, and publish to agents.</p><SellingIllustration /></div></MotionReveal></div></div></section>

      <section id="connect" className="px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><MotionReveal className="max-w-3xl"><p className="text-sm font-semibold text-primary">Connect anything</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] md:text-5xl">Keep the business. Add the agent layer.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Caravel reads the API you already operate, then turns its operations into documented, priced products that agents can discover and use.</p></MotionReveal><MotionReveal delay={100}><ConnectionIllustration /></MotionReveal></div></section>

      <section id="rails" className="border-y border-border bg-black/10 px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><MotionReveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold text-primary">Use the right payment rail</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] md:text-5xl">The product and policy choose how money moves.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Small machine payment, controlled card purchase, high-value escrow, or the checkout you already operate.</p></MotionReveal><MotionReveal delay={100}><RailIllustration /></MotionReveal></div></section>

      <section className="px-5 py-24 text-center md:px-8 md:py-32"><MotionReveal className="mx-auto max-w-4xl"><p className="text-sm font-semibold text-primary">Agent-ready commerce without rebuilding your company</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em] md:text-6xl">Connect once. Govern every transaction.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Give agents a safe way to buy what your company needs and sell what your company already offers.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/dashboard">Open the platform<ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/api/openapi">View the live API</Link></Button></div></MotionReveal></section>
    </main>

    <footer className="border-t border-border px-5 py-8 md:px-8"><div className="mx-auto flex max-w-[90rem] flex-col gap-5 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><CaravelMark className="size-8" /><div><p className="font-medium text-foreground">Caravel</p><p>API product infrastructure for the agent web</p></div></div><div className="flex gap-6"><Link href="/dashboard" className="hover:text-foreground">Dashboard</Link><Link href="/api/openapi" className="hover:text-foreground">API</Link><a href="#platform" className="hover:text-foreground">Platform</a></div></div></footer>
  </div>;
}
