import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { buildApiProduct } from "./build.mjs";
import { normalizeOpenApi } from "./connectors.mjs";
import { installApiProduct, uninstallApiProduct } from "./install.mjs";
import { createReadinessReport } from "./report.mjs";
import { writeWorkspace } from "./workspace.mjs";

describe("Caravel installer", () => {
  it("installs discovery, gateway, access, and docs files", async () => {
    const root = await mkdtemp(join(tmpdir(), "caravel-install-source-"));
    const target = await mkdtemp(join(tmpdir(), "caravel-install-target-"));
    await writeFile(resolve(target, "package.json"), JSON.stringify({ name: "target", dependencies: {} }));
    const source = resolve(root, "openapi.json");
    const openapi = { openapi: "3.1.0", info: { title: "Test API", version: "1" }, paths: { "/ping": { get: { summary: "Ping" } } } };
    await writeFile(source, JSON.stringify(openapi));
    const catalog = normalizeOpenApi(openapi, source);
    await writeWorkspace(root, catalog, createReadinessReport(catalog));
    await buildApiProduct(root, { upstreamBaseUrl: "https://api.example.com" });
    await installApiProduct(root, { target, installDependencies: false });
    expect(JSON.parse(await readFile(resolve(target, "public/.well-known/caravel.json"), "utf8")).upstreamBaseUrl).toBe("https://api.example.com");
    expect(await readFile(resolve(target, "src/app/api/caravel/[...path]/route.ts"), "utf8")).toContain("withCaravelAccess");
    expect(await readFile(resolve(target, "lib/caravel-access.ts"), "utf8")).toContain("CARAVEL_API_KEYS");
    expect(await readFile(resolve(target, "public/.well-known/agent-card.json"), "utf8")).toContain("Seller Agent");
    expect(await readFile(resolve(target, "src/app/caravel-docs/page.tsx"), "utf8")).toContain("DocsPage");
    expect(await readFile(resolve(target, "src/app/caravel-docs/reference/[operation]/page.tsx"), "utf8")).toContain("OpenAPIReference");
    expect(await readFile(resolve(target, "src/app/caravel-docs/openapi-reference.tsx"), "utf8")).toContain("createOpenAPIPage");
    expect(await readFile(resolve(target, "src/app/caravel-docs/loading.tsx"), "utf8")).toContain("Loading documentation");
    expect(await readFile(resolve(target, "src/app/caravel-docs/caravel-docs.css"), "utf8")).toContain("height: 52px");
    expect(await readFile(resolve(target, "src/app/caravel-docs/quickstart/page.tsx"), "utf8")).toContain("Quickstart");
    expect(await readFile(resolve(target, "src/app/caravel-docs/sdks/page.tsx"), "utf8")).toContain("SDKs");
    expect(await readFile(resolve(target, "src/app/caravel-docs/guides/[operation]/page.tsx"), "utf8")).toContain("When to use this endpoint");
    expect(await readFile(resolve(target, "src/app/caravel-docs/snippets/page.tsx"), "utf8")).toContain("Embeds");
    expect(await readFile(resolve(target, "public/caravel-openapi.json"), "utf8")).toContain('"openapi": "3.1.0"');
    await uninstallApiProduct(target);
    await expect(readFile(resolve(target, "public/.well-known/caravel.json"), "utf8")).rejects.toThrow();
  });
});
